# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
#            name='Subscribers',
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=128)),
                ('subscraber_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
